// AI Error Dictionary — click a Python error to get an AI explainer.

const PY_ERRORS = [
  { name: "SyntaxError",          group: "Parsing" },
  { name: "IndentationError",     group: "Parsing" },
  { name: "TabError",             group: "Parsing" },
  { name: "NameError",            group: "Scope" },
  { name: "UnboundLocalError",    group: "Scope" },
  { name: "TypeError",            group: "Types" },
  { name: "ValueError",           group: "Types" },
  { name: "AttributeError",       group: "Types" },
  { name: "IndexError",           group: "Lookup" },
  { name: "KeyError",             group: "Lookup" },
  { name: "ZeroDivisionError",    group: "Math" },
  { name: "OverflowError",        group: "Math" },
  { name: "FloatingPointError",   group: "Math" },
  { name: "ArithmeticError",      group: "Math" },
  { name: "FileNotFoundError",    group: "I/O" },
  { name: "PermissionError",      group: "I/O" },
  { name: "IsADirectoryError",    group: "I/O" },
  { name: "NotADirectoryError",   group: "I/O" },
  { name: "OSError",              group: "I/O" },
  { name: "IOError",              group: "I/O" },
  { name: "StopIteration",        group: "Iteration" },
  { name: "StopAsyncIteration",   group: "Iteration" },
  { name: "RuntimeError",         group: "Runtime" },
  { name: "RecursionError",       group: "Runtime" },
  { name: "NotImplementedError",  group: "Runtime" },
  { name: "ModuleNotFoundError",  group: "Imports" },
  { name: "ImportError",          group: "Imports" },
  { name: "MemoryError",          group: "System" },
  { name: "SystemError",          group: "System" },
  { name: "KeyboardInterrupt",    group: "System" },
  { name: "AssertionError",       group: "Debug" },
  { name: "UnicodeError",         group: "Encoding" },
  { name: "UnicodeDecodeError",   group: "Encoding" },
  { name: "UnicodeEncodeError",   group: "Encoding" },
];

function renderErrors() {
  const sidebar = document.getElementById("sidebar");
  const main = document.getElementById("main");

  let query = "";
  let activeName = location.hash.slice(1) || null;

  function paintSidebar() {
    const byGroup = {};
    PY_ERRORS.forEach(e => (byGroup[e.group] = byGroup[e.group] || []).push(e));
    sidebar.innerHTML = `
      <div style="padding:8px 10px;border-bottom:1px solid var(--border);">
        <input id="err-search" placeholder="Filter…" value="${escapeHTML(query)}" style="width:100%;" />
      </div>
      ${Object.keys(byGroup).map(g => `
        <div class="sb-group">${escapeHTML(g)}</div>
        ${byGroup[g].filter(e => !query || e.name.toLowerCase().includes(query.toLowerCase())).map(e => `
          <a class="sb-item ${activeName === e.name ? "active" : ""}" data-name="${e.name}">
            <span style="font-family:var(--font-mono);font-size:12px;">${e.name}</span>
          </a>
        `).join("")}
      `).join("")}
    `;
    sidebar.querySelector("#err-search").oninput = ev => { query = ev.target.value; paintSidebar(); };
    sidebar.querySelectorAll("[data-name]").forEach(el => el.onclick = () => {
      activeName = el.dataset.name;
      location.hash = activeName;
      paintSidebar();
      paintEntry();
    });
  }

  function paintEntry() {
    if (!activeName) {
      main.innerHTML = `
        <div class="tabs"><div class="tab active">Python Errors</div></div>
        <div class="page-wide">
          <div class="h1">Python error dictionary</div>
          <div class="subtle" style="margin-bottom:14px;">Click any exception to see what it means, what causes it, and how to fix it. Explanations are generated by AI.</div>
          ${recentMistakesHTML()}
          <div class="h2">All errors</div>
          <div class="err-grid">
            ${PY_ERRORS.map(e => `
              <div class="err-chip" data-name="${e.name}">${e.name}</div>
            `).join("")}
          </div>
        </div>
      `;
      main.querySelectorAll("[data-name]").forEach(el => el.onclick = () => {
        activeName = el.dataset.name;
        location.hash = activeName;
        paintSidebar();
        paintEntry();
      });
      return;
    }
    main.innerHTML = `
      <div class="tabs"><div class="tab active">${escapeHTML(activeName)}</div></div>
      <div class="page-narrow">
        <a href="#" id="back-link" class="subtle">← All errors</a>
        <div class="h1" style="font-family:var(--font-mono);color:var(--red);margin-top:6px;">${escapeHTML(activeName)}</div>
        <div class="card" style="margin-top:14px;">
          <div id="entry-body"><div class="subtle">Loading explainer…</div></div>
        </div>
      </div>
    `;
    document.getElementById("back-link").onclick = (e) => {
      e.preventDefault();
      activeName = null;
      location.hash = "";
      paintSidebar();
      paintEntry();
    };
    const target = document.getElementById("entry-body");
    if (!AI.available()) {
      target.innerHTML = `<div class="feedback bad">Configure a Groq key in <a href="settings.html#ai">Settings</a> to load explanations.</div>`;
      return;
    }
    AI.into(target, PROMPTS.errorEntry(activeName), { maxTokens: 900 });
  }

  function recentMistakesHTML() {
    const errs = Tracker.ensure().errors || {};
    const top = Object.entries(errs).sort((a,b) => b[1] - a[1]).slice(0, 6);
    if (!top.length) return "";
    return `
      <div class="card" style="margin-bottom:14px;">
        <div style="font-weight:600;color:var(--fg-strong);margin-bottom:6px;">Errors you've hit</div>
        <div style="display:flex;gap:6px;flex-wrap:wrap;">
          ${top.map(([n, c]) => `<a class="tag red" style="cursor:pointer;text-decoration:none;" href="#${n}">${n} <span style="opacity:0.6;">×${c}</span></a>`).join("")}
        </div>
      </div>
    `;
  }

  paintSidebar();
  paintEntry();
  window.addEventListener("hashchange", () => {
    activeName = location.hash.slice(1) || null;
    paintSidebar(); paintEntry();
  });
}
